### ISSUE TITLE
Submission Review

### ISSUE THREAD

**Issue by ivan-adakerja** [Rahardirizky/facebook-chat-bot-adakerja#1]
Hi @Rahardirizky ! I am Ivan 👋 😄 from AdaKerja
Thanks for the submission, here I have my review result for you.

- [-] no test
- [+] code style looks neat and folder structure clear
- [-] use memory db
- [-] db is using fs.readFile / fs.writeFile. both function is async, they could create race condition
- [-] state is not so good, its based on how many message on db. not scalable if we want to have repeated question. ex. if inputted birthday is not valid, user might need to ask again.
- [+] birthday calculation correct

what do you say?

**Comment by Rahardirizky** [comment]
HI @ivan-adakerja ! 
Thank You so much for your review on my work.

I actually realized the flaws on my code like you mentioned above. By looking at your review I think I can improve this project based on your review. I think I will try to improve the code and be right back to you.
